version: '3.8'

services:
    web:
        build: .
        ports:
            - '8000:5000'
        volumes:
            - .:/app
            - ./autoquiz.db:/app/autoquiz.db
        environment:
            - FLASK_APP=app.py
            - FLASK_ENV=development
            - DATABASE_URI=sqlite:///autoquiz.db
        restart: unless-stopped
